### Get access token from CIAM via the internal app (nodejs API) for the subsequent API operations
# @name GetAccessTokenFromCIAMInternal
GET {{helperApiBaseUrl}}/security/token/{{environmentName}} HTTP/1.1
Content-Type: application/json
Accept: application/json

### Bulk enrol USI
# @name BulkEnrolUsi
POST {{usiApiBaseUrl}}/enrolment/enrol/bulk HTTP/1.1
Content-Type: application/json
Accept: application/json
Ocp-Apim-Subscription-Key: {{apimSubscriptionKey}}
Authorization: Bearer {{GetAccessTokenFromCIAMInternal.response.body.access_token}}

{
    "school_ageid": 9991234,
    "data": [
        {
            "usi": "KZXSHVQW7Z",
            "single_name": "",
            "family_name": "Ryan",
            "date_of_birth": "1974-12-04",
            "local_student_identifier": "evanryan123"
        }
    ]
}
