### Get client assertion via the internal app (nodejs API) for the access token requests
# @name GetClientAssertion
GET {{helperApiBaseUrl}}/security/assertion/{{environmentName}} HTTP/1.1
Content-Type: application/json
Accept: application/json

### Get access token from CIAM for the subsequent API operations
# @name GetAccessTokenFromCIAM
POST https://login.microsoftonline.com/{{ciamTenant}}/oauth2/v2.0/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json

client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer
&grant_type=client_credentials
&client_id={{machineClientId}}
&scope={{usiApplicationId}}/.default
&client_assertion={{GetClientAssertion.response.body.client_assertion}}
